services:
  # A Docker web service
  - type: web
    name: main
    env: docker
    repo: https://github.com/automatisch/automatisch # optional
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings

databases:
  - name: elephant
    plan: free
    databaseName: mydb # optional (Render may add a suffix)
